nothing
Anuken/CoreBot pull request #33
Opened 2022-04-24 14:14 UTC by DeltaNedas

mrajc

2022-04-24 14:27 UTC, markozajc commented
never

2022-04-24 14:28 UTC, markozajc requested changes
chungus

2022-04-24 14:28 UTC, DeltaNedas commented
always

2022-04-24 14:32 UTC, WilloIzCitron approved these changes
mark down

2022-04-24 14:33 UTC, markozajc commented
nooooo

2022-04-24 14:52 UTC, Anuken commented
marko zajc

2022-04-24 15:15 UTC, DeltaNedas commented
nice scam anuke you have been timed out for 1 year(s)

2022-04-24 15:21 UTC, markozajc commented
idiot he is the owner enjoy your net.dv8tion.jda.api.exceptions.HierarchyException

2023-04-14 09:32 UTC, deltanedas commented
timeout expire

2023-04-16 02:20 UTC, Anuken commented
finally

2025-11-25 08:05 UTC, closed without merging

2025-11-25 08:17 UTC, markozajc commented
true

2025-11-25 08:19 UTC, deltanedas commented
majc has won

2025-12-15 05:09 UTC, Anuken commented
marko zajc

2025-12-15 05:35 UTC, deltanedas commented
marko zajc